org: wildflowerschools
app: wf-fetch-tc-data
service: wf-fetch-tc-data-serverless

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9

functions:
  fetch_and_store_rosters_current:
    handler: handler.fetch_and_store_rosters_current
    environment:
      # Transparent Classroom credentials for fetching data
      TRANSPARENT_CLASSROOM_USERNAME: $(param:TRANSPARENT_CLASSROOM_USERNAME}
      TRANSPARENT_CLASSROOM_PASSWORD: $(param:TRANSPARENT_CLASSROOM_PASSWORD}
      # Google Sheets destination
      SPREADSHEET_NAME_BASE: $(param:SPREADSHEET_NAME_BASE}
      RECIPIENT_EMAIL_ADDRESS: $(param:RECIPIENT_EMAIL_ADDRESS}
      # Google service account auth info (download as JSON when service account is created)
      TC_DOWNLOAD_GOOGLE_AUTH_TYPE: $(param:TC_DOWNLOAD_GOOGLE_AUTH_TYPE}
      TC_DOWNLOAD_GOOGLE_AUTH_PROJECT_ID: $(param:TC_DOWNLOAD_GOOGLE_AUTH_PROJECT_ID}
      TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY_ID: $(param:TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY_ID}
      TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY: $(param:TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY}
      TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_EMAIL: $(param:TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_EMAIL}
      TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_ID: $(param:TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_ID}
      TC_DOWNLOAD_GOOGLE_AUTH_AUTH_URI: $(param:TC_DOWNLOAD_GOOGLE_AUTH_AUTH_URI}
      TC_DOWNLOAD_GOOGLE_AUTH_TOKEN_URI: $(param:TC_DOWNLOAD_GOOGLE_AUTH_TOKEN_URI}
      TC_DOWNLOAD_GOOGLE_AUTH_AUTH_PROVIDER_X509_CERT_URL: $(param:TC_DOWNLOAD_GOOGLE_AUTH_AUTH_PROVIDER_X509_CERT_URL}
      TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_X509_CERT_URL: $(param:TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_X509_CERT_URL}
      TC_DOWNLOAD_GOOGLE_AUTH_UNIVERSE_DOMAIN: $(param:TC_DOWNLOAD_GOOGLE_AUTH_UNIVERSE_DOMAIN}
    events:
      - http:
          path: /
          method: get