service: wf-fetch-tc-data-serverless

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9

functions:
  fetch_and_store_rosters_current:
    handler: handler.fetch_and_store_rosters_current
    environment:
      # Transparent Classroom credentials for fetching data
      TRANSPARENT_CLASSROOM_USERNAME: ${secrets:TRANSPARENT_CLASSROOM_USERNAME}
      TRANSPARENT_CLASSROOM_PASSWORD: ${secrets:TRANSPARENT_CLASSROOM_PASSWORD}
      # Google Sheets destination
      SPREADSHEET_NAME_BASE: ${secrets:SPREADSHEET_NAME_BASE}
      RECIPIENT_EMAIL_ADDRESS: ${secrets:RECIPIENT_EMAIL_ADDRESS}
      # Google service account auth info (download as JSON when service account is created)
      TC_DOWNLOAD_GOOGLE_AUTH_TYPE: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_TYPE}
      TC_DOWNLOAD_GOOGLE_AUTH_PROJECT_ID: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_PROJECT_ID}
      TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY_ID: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY_ID}
      TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_PRIVATE_KEY}
      TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_EMAIL: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_EMAIL}
      TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_ID: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_ID}
      TC_DOWNLOAD_GOOGLE_AUTH_AUTH_URI: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_AUTH_URI}
      TC_DOWNLOAD_GOOGLE_AUTH_TOKEN_URI: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_TOKEN_URI}
      TC_DOWNLOAD_GOOGLE_AUTH_AUTH_PROVIDER_X509_CERT_URL: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_AUTH_PROVIDER_X509_CERT_URL}
      TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_X509_CERT_URL: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_CLIENT_X509_CERT_URL}
      TC_DOWNLOAD_GOOGLE_AUTH_UNIVERSE_DOMAIN: ${secrets:TC_DOWNLOAD_GOOGLE_AUTH_UNIVERSE_DOMAIN}
    events:
      - http:
          path: /
          method: get